### ISSUE TITLE
Problem with version 1.3

### ISSUE THREAD

**Issue by karco** [claudegel/sinope-gt125#28]
Hello, since version 1.3 I have 4 thermostats which have lost communication with Home Assistant.

2021-01-03 11:13:54 ERROR (MainThread) [homeassistant.components.climate] neviweb: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb/climate.py", line 177, in update
    self._away_temp = float(device_data[ATTR_AWAY_SETPOINT])
KeyError: 'roomSetpointAway'
2021-01-03 11:13:56 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform neviweb is taking over 10 seconds.
2021-01-03 11:13:56 ERROR (MainThread) [homeassistant.components.climate] neviweb: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb/climate.py", line 177, in update
    self._away_temp = float(device_data[ATTR_AWAY_SETPOINT])
KeyError: 'roomSetpointAway'
2021-01-03 11:13:57 ERROR (MainThread) [homeassistant.components.climate] neviweb: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb/climate.py", line 177, in update
    self._away_temp = float(device_data[ATTR_AWAY_SETPOINT])
KeyError: 'roomSetpointAway'
2021-01-03 11:13:58 ERROR (MainThread) [homeassistant.components.climate] neviweb: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb/climate.py", line 177, in update
    self._away_temp = float(device_data[ATTR_AWAY_SETPOINT])
KeyError: 'roomSetpointAway'

**Comment by karco** [comment]
neviweb:
  username:       !secret sinope_neviweb_username
  password:       !secret sinope_neviweb_password
  scan_interval:  300

**Comment by claudegel** [comment]
Sorry I didn't see your issue before because you've open it in the wrong component. Your in sinope-GT125 for direct connect to the GT125 without Neviweb. But it's not a problem.
You say that three thermostats give error. are they all the thermostats you have on that custom_component or you have other that are ok.
It look like your device or Neviweb are not responding. device_data is empty so climate.py do not receive device_data[ATTR_AWAY_SETPOINT]. 
Do you have more log. something like 
[custom_components.neviweb.climate] Error in reading device neviweb  climate Chambre 1: ({'errorCode': 'ReadTimeout'}), too slow to respond or busy.
If you have other thermostats that are working OK then just push the two button on the thermostat simultaneously to reconnect them to the GT125. 
I'll push a new bersion tonight for the neviweb custom component

**Comment by claudegel** [comment]
Please note that on Sunday, Sinopé is doing a lot of merges as they plan to set out new services in mid January. It could be why you didn't receive your devices data. Le me know if it is back to normal tomorrow.
You can update to release  version 1.4

**Comment by karco** [comment]
Hello claudegel, thank you for your reply. I have 5 thermostats which are functional and 4 non-functional.

**Comment by karco** [comment]
If I look on the Neviweb interface, all my thermostats are connected.

**Comment by karco** [comment]
At the second restart this morning, all thermostats are connected. I restarted in debug mode for Neviweb and everything looks okay.

**Comment by karco** [comment]
Sorry for the spam. I have removed debug mode and now have a thermostat that displays N/A.

2021-01-04 09:43:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for neviweb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-04 09:44:14 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform neviweb is taking over 10 seconds.
2021-01-04 09:44:17 WARNING (SyncWorker_11) [custom_components.neviweb.climate] Cannot update neviweb climate Salle de Lavage: {'error': {'code': 'DVCCOMMTO', 'data': {'retry': 2}}}. Device is busy or does not respond quickly enough.

**Comment by karco** [comment]
After a few minutes, the disconnected thermostat returned. All my thermostat are now visible in the home assistant.

Weird ...

**Comment by claudegel** [comment]
The neviweb custom component is talking to the Neviweb portal from Sinopé. The answer you got:
{'error': {'code': 'DVCCOMMTO', 'data': {'retry': 2}}}. Device is busy or does not respond quickly enough. is from the Neviweb portal telling you that the device climate Salle de Lavage is not responding to the request from Neviweb portal.
DVCCOMMTO is device communication to. If you go to Neviweb portal at the same time you have a missing device you should notice that the square icon for that device is blinking or is grey out. As I told before I've noticed that frequently on Sunday the Neviweb portal is slow to respond and it look like that Sinopé is sending update to the devices at that time.
One thing you can do is to push the two button on the thermostat at the same time. This force a reconnect to the GT125.
You can also check the RSSI attribute from the device that are ok and the one that are not responding. This is the signal level between the device and the GT125.
If the signal is not good for some devices you can try what I did once. I had a thermostat and few light that had a poor connection with the GT125. So I reset them and re link them one by one starting with the one that are closer to the GT125.  That way the devices that are closer will act as a relay for the one that are far and improve the connection stability.

here is the procedure for this in french from Sinopé. Youwill probably have to reconfigure your automation as the dvice id will change.
```
Réinitialiser la connexion
DM2500RF + SW2500RF

1- Débrancher l’alimentation du GT125;
2- Appuyez sur le bouton du haut de l’interrupteur/gradateur pendant 10 secondes ou jusqu’à ce
que la DEL clignote en jaune;
3- Relâchez le bouton et enfoncez-le à nouveau pendant 10 secondes ou jusqu’à ce que la DEL
clignote en rouge;
4- Relâchez le bouton, la DEL s’éteindra.
5- Rebranchez l’alimentation du GT125

TH1120RF

1- Débrancher l’alimentation du GT125;
2- Maintenir le bouton du bas du thermostat jusqu’à ce qu’apparaisse le menu de configuration;
3- Appuyer une fois sur le bouton du bas et l’option de déconnecter devrait apparaitre (affiche «
No » et « Connect Reset »);
4- Appuyer sur le bouton du haut pour choisir « Yes »;
5- Appuyer sur le bouton du bas pour confirmer et l’écran de confirmation apparait (affiche «
sure », « no » et « Connect reset »);
6- Appuyer encore sur le bouton du haut pour choisir « Yes »;
7- Appuyer sur le bouton du bas pour confirmer; « Clr » affiche.
8- Rebranchez l’alimentation du GT125

TH1300RF et TH1400RF

1- Débrancher l’alimentation du GT125;
2- Appuyez sur le bouton du bas jusqu'à ce que le menu de configuration apparaisse.
3- Appuyez sur les deux boutons (haut et bas) en même temps jusqu’à ce que le texte "RST"
s'affiche à l'écran du thermostat.
4- Appuyez sur le bouton du bas pour choisir "YES".
5- Appuyez sur les deux boutons (haut et bas) en même temps pour confirmer votre choix.
6- Le texte "SURE" s'affiche à l'écran. Vous appuyez sur le bouton du bas pour sélectionner "YES".
7- Appuyez sur les deux boutons (haut et bas) en même temps pour confirmer votre choix.
8- Le texte "CLR" s'affiche à l'écran.
9- Rebranchez l’alimentation du GT125

RM3200RF

1- Débrancher l’alimentation du GT125;
2- Appuyez sur le bouton RF et le bouton « on/off » pendant 10 secondes ou jusqu’à ce que les
DELs clignotent (orange et vert);
3- Relâchez les boutons, la DEL RF s’éteindra.
4- Rebranchez l’alimentation du GT125
```

**Comment by claudegel** [comment]
I think I've found the bug. I've push a new release 1.4.1 please test

**Comment by karco** [comment]
Hello claudegel, thank you for your investigation. I applied the update this morning.

From what I can see, you live in Varenne. I presume we can speak to each other in French?

**Comment by claudegel** [comment]
Yes I speak french, english and spanish.

**Comment by karco** [comment]
Suite à l'installation de la version 1.4.2, la collecte des données semble beaucoup plus précise et 100% de mes thermostats se connectent sans problème.

![2021-01-08 12_20_46-Overview - Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/17675437/104045541-b6523e00-51ac-11eb-8fd9-df7b46814619.png)

Merci encore pour ton aide.

**Comment by claudegel** [comment]
Fait plaisir. Si tu as autre chose n'hesites pas.
Tu peux aussi suivre dle developpement sur 
https://community.home-assistant.io/t/sinope-line-voltage-thermostats/17157/641
Je vais faire plein de mise a jour en fin de semaine
