### ISSUE TITLE
last update problem

### ISSUE THREAD

**Issue by olivierjag2** [claudegel/sinope-gt125#44]
hi, since the last update 1.5.4, I have this error message.

I try to reinstall, I can not reboot home assistant... 

[140074111939488] The system cannot restart because the configuration is not valid: Integration error: sinope - Integration 'sinope' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 599, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: sinope - Integration 'sinope' not found.

**Comment by claudegel** [comment]
Sorry I miss your issue.
This custom component is installed in config/custom_components/sinope
If the download didn't succeed than this directory will be empty.
Retry the download via HACS it should work

**Comment by claudegel** [comment]
If this prevent you from rebooting HA then comment out the lines about sinope in configuration.yaml and restart HA. This way you'll be able to redownload Sinope GT125 again

**Comment by olivierjag2** [comment]
ok thx

**Comment by claudegel** [comment]
Did you succeed to load the sinope-GT125 ?

**Comment by olivierjag2** [comment]
Yes
