### ISSUE TITLE
Platform not found (No module named 'aiofiles')

### ISSUE THREAD

**Issue by dcouture-ca** [claudegel/sinope-gt125#66]
Hi, i try to setup my thermostat with hass 2024.6.4 and i receive this error.

I try to install the module with the command: pip3 install aiofiles

But i continue to get the error. My setup is based ont proxmox  Home Assistant Core LXC

**Comment by claudegel** [comment]
You don't need pip3 to install the sinope-Gt125 custom component. just use HACS to install it. Then go in config/custom_components/sinope and run the command python3 device.py.
Read the doc in the readme.md
https://github.com/claudegel/sinope-gt125/tree/master

**Comment by dcouture-ca** [comment]
The full msg is: ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'sinope.climate': Platform not found (No module named 'aiofiles').

I got this error in hass log file after installation of the module via HACS and restart home assistant. I run the command device.py with success and added my device.

**Comment by claudegel** [comment]
aiofiles is part of python and is used to read config file that contain all the devices you have registered with device.py
The file is located in /config/.storage/sinope_devices.json and sinope_devices_2.json if you have two GT125.
Once HA is started we load the data from those files into HA entities list.
So if you see your devices in HA, everything is fine. It is probably a bug in Hacs that can't find that module during installation of sinope-GT125
I don't have any message about aiofiles being deprecated but I'll watch and will replace that module if it is the case.
Let me know is this message come back at each HA restart.

**Comment by jcordeiro73** [comment]
Hi
I have the same problem 
It doesn't work
Before I have the neviweb version and it stopped working after a system reboot. Same error that I have as gt125. I think it's a hass problem but I don't know how to correct it

**Comment by jcordeiro73** [comment]
This morning, I installed core 2024.8.1, 2024.8.0 and core 2024 7.4,.same problem with both neviweb and gt125

**Comment by jcordeiro73** [comment]
Hi just installed a new fresh installation only with HASS, HACS and neviweb
Error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 78, in setup
    data = NeviwebData(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 102, in __init__
    self.neviweb_client = NeviwebClient(username, password, network, network2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 133, in __init__
    self.__post_login_page()
  File "/config/custom_components/neviweb/__init__.py", line 156, in __post_login_page
    raise PyNeviwebError("Cannot log in")
custom_components.neviweb.PyNeviwebError: Cannot log in

**Comment by jcordeiro73** [comment]
With sinope : 

➜  sinope python3 device.py  (IT WORKS)
Which GT125 you want to connect to: 1 or 2 ?
^CTraceback (most recent call last):
  File "/homeassistant/custom_components/sinope/device.py", line 180, in <module>
    network = input()
              ^^^^^^^
KeyboardInterrupt

➜  sinope python3 climate.py (Doesnt WORK)
Traceback (most recent call last):
  File "/homeassistant/custom_components/sinope/climate.py", line 10, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
➜  sinope

**Comment by claudegel** [comment]
Cannot log in error is when your passord or user name are not good. If you set your scan_interval below 300 your will be disconnected from neviweb because you poll too agressively. If you set it above 600 you will be disconected from Neviweb because it report as inactiv session.
Add this to configuration.yaml to get more logging
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb: debug
    custom_components.sinope: debug
```
About python3 climate.py, you can't run that file alone. It is part of HA custom_component. It must be run by HA. Only device.py is set to run alone with python3 device.py
