### ISSUE TITLE
Sinope-1 Fails to load after restart of HA 2024.10.0 & 2025.10.1

### ISSUE THREAD

**Issue by foxxcomm** [claudegel/sinope-gt125#68]
Home Assistant Core (Hyper-V): 2024.10.0
Sinope-1 Version: v2.2.2

Starting with HA 2024.10.0, we are seeing this error at startup and Sinope-1 no longer functions. We have tried re-moving and installing it:

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 02:26:21 (1 occurrences)
Last logged: 02:26:21

Error during setup of component neviweb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 78, in setup
    data = NeviwebData(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 102, in __init__
    self.neviweb_client = NeviwebClient(username, password, network, network2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 134, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb/__init__.py", line 179, in __get_network
    raw_res = requests.get(LOCATIONS_URL + self._account, headers=self._headers,
                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by foxxcomm** [comment]
Tried HA 2024.10.1. Looks like the same issue:

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 02:36:59 (1 occurrences)
Last logged: 02:36:59

Error during setup of component neviweb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 78, in setup
    data = NeviwebData(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 102, in __init__
    self.neviweb_client = NeviwebClient(username, password, network, network2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb/__init__.py", line 134, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb/__init__.py", line 179, in __get_network
    raw_res = requests.get(LOCATIONS_URL + self._account, headers=self._headers,
                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by foxxcomm** [comment]
Please Disregard. Turned out to be related to our Neviweb account being merged by Sinope with their new user account structure and once we reset the password all is good again. Thank You

**Comment by foxxcomm** [comment]
Please Disregard. Turned out to be related to our Neviweb account being merged by Sinope with their new user account structure and once we reset the password all is good again. Thank You
