### ISSUE TITLE
Possible breaking change for this integration in core 2024.12.0.

### ISSUE THREAD

**Issue by sbeaudoin** [claudegel/sinope-gt125#71]
Upgraded to core 2024.12.0 and since then, the integration crash with the following :

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:825
integration: Climate (documentation, issues)
First occurred: 05:34:12 (3 occurrences)
Last logged: 05:34:12

Error adding entity None for domain climate with platform sinope
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 530, in capability_attributes
    data[ATTR_SWING_HORIZONTAL_MODES] = self.swing_horizontal_modes
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "src/propcache/_helpers_c.pyx", line 80, in propcache._helpers_c.cached_property.__get__
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 727, in swing_horizontal_modes
    return self._attr_swing_horizontal_modes
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
AttributeError: 'SinopeThermostat' object has no attribute '__attr_swing_horizontal_modes'. Did you mean: '_attr_swing_horizontal_modes'?
```

This seems to be due to a new fonctionality who requires all climate integration to declare the new attribute "_attr_swing_horizontal_modes".  Opened a [HA core ticket](https://github.com/home-assistant/core/issues/132437) about this because if my interpretation is right, it could break all climate integration who don't declare this attribute.

I think it could also be solved if you declare this attribute on your side.

Don't flame me if I am wrong, I am new to HA and only trying to help.

**Comment by sbeaudoin** [comment]
Oh!  Pis salut de Québec, je viens de voir ta bio.

**Comment by omelettedufromagee** [comment]
Salut! I have the same issue, this comes from this change in HA core:
https://github.com/home-assistant/core/commit/a7db35c76cbffbc42a2af65e6ec9c2fb57089fae

**Comment by sbeaudoin** [comment]
Even though the problem impact possibly every climate implementation, HA consider it out of their responsability and they closed the ticket 🙄😠.

**Comment by omelettedufromagee** [comment]
I rolled back the core version. I think HA messed up, they might have a change to remove the supported_features warning. So it could be resolved in upcoming update.

**Comment by sbeaudoin** [comment]
Maybe I will make a pull request, but in the meantime, here are the steps to resolve it manually :

1. If not already installed, install Visual Studio Code in HA (VSCode - The tool name is "Studio Code Server")
2. In VSCode, go to the /config/custom_components/sinope/climate.py file.
3. At about line 399, make sure to add the two lines begining with "_attr_swing".

```
class SinopeThermostat(ClimateEntity):
    """Implementation of a Sinope thermostat."""

    _enable_turn_on_off_backwards_compatibility = False
    _attr_temperature_unit = UnitOfTemperature.CELSIUS
    _attr_swing_horizontal_modes = []
    _attr_swing_horizontal_mode = ""
```

4. Save the file (Ctrl-S) and restart HA.

**Comment by claudegel** [comment]
Sorry I was busy on my other custom_component neviweb130 with a major code change.
I forgot to add the patch for swing_horizontal.
I'll add the changes and make a release

**Comment by claudegel** [comment]
Do you have version 1.7.1. swing mode should be fixed in that one.
